[semver:patch] Improve sonar command
ClouDesire/circleci-orbs pull request #15
Opened 2020-11-25 09:28 UTC by PPFerrari

ref https://github.com/ClouDesire/support/issues/4459

2020-11-25 12:02 UTC, PPFerrari commented
Prima di chiudere, vorrei provare lo step anche su un repo non maven. Potrebbe andare bene `control-panel`, dove ho visto hanno già fatto una modifica simile? così approfittiamo anche per allinearlo.

2020-11-25 12:47 UTC, PPFerrari commented
Inoltre, la variable `SONAR_SOURCES` ora dovrebbe essere passata a parte, rispetto a `SONAR_OPTS`. Conviene toglierla e far passare tutto tramite `SONAR_OPTS`?
In tal caso, potremmo aggiungere un controllo per verificare che, in caso di progetti non-maven, all'interno di `SONAR_OPTS` esista `-Dsonar.sources`

2020-11-25 13:12 UTC, gionn requested changes

2020-11-25 13:12 UTC, gionn commented on src/scripts/sonar.sh
> +            -Dsonar.pullrequest.base=master"
mmm, va gestito in un qualche modo perché i nuovi repo avranno `main`

forse c'è una env var circleci?

2020-11-25 13:12 UTC, gionn commented on src/scripts/sonar.sh
> +    fi
a leggere il readme https://github.com/bellingard/sonar-scanner-npm sembra sia solo un wrapper, secondo me non ha senso gestirlo ad hoc, si usa la cli anche per i progetti con npm e fine (così non serve installare anche il plugin npm in ogni progetto)

2020-11-25 13:41 UTC, PPFerrari commented on src/scripts/sonar.sh
> +    fi
perfetto

2020-11-25 13:41 UTC, PPFerrari commented on src/scripts/sonar.sh
> +    fi
per SONAR_OPTS, cosa ne pensi?

2020-11-25 15:17 UTC, gionn commented on src/scripts/sonar.sh
> +  mkdir -p $SONAR_DIR
metti in cache anche lui

2020-11-25 15:19 UTC, gionn requested changes

2020-11-25 15:19 UTC, gionn commented on src/scripts/sonar.sh
> +        unset SONAR_GITHUB_TOKEN
penso puoi buttare via il ramo else, serviva con la vecchia implementazione

2020-11-25 15:19 UTC, gionn commented on src/scripts/sonar.sh
> +    # Preview mode when running in a Pull Request
```suggestion
```

già si capisce che fa

2020-11-26 09:38 UTC, gionn commented on src/scripts/sonar_get_server_version.sh
> +source $BASH_ENV
è più semplice se scrivi la versione in un file e usi `{{ checksum "filename" }}`, così come hai fatto (ammesso che funzioni) hai solo la versione del server nella chiave della cache (si sopravvive anche con un checksum illeggibile)

2020-11-26 10:42 UTC, PPFerrari commented on src/scripts/sonar_get_server_version.sh
> +source $BASH_ENV
ho fatto così alla fine, perchè `{{ .Environment.variableName }}` non funziona purtroppo.

2020-11-26 12:02 UTC, gionn requested changes

2020-11-26 12:02 UTC, gionn commented on src/commands/test_sonar.yml
> +      name: Get SonarQube Server Version
```suggestion
      name: Generate sonar_version.txt
```
così è più chiaro l'intento

scambia i due restore cache o spoposta questo più sotto così è ancora più esplicito il quando viene usato

2020-11-26 12:02 UTC, gionn commented on src/commands/test_sonar.yml
>        name: Execute sonar
```suggestion
      name: Execute sonar scan
```

2020-11-26 12:02 UTC, gionn commented on src/scripts/sonar.sh
> +SONAR_VERSION=${SONAR_VERSION:-4.2.0.1873}
qui stai ripetendo quello già definito nello yaml

2020-11-26 12:02 UTC, gionn commented on src/scripts/sonar.sh
> +  echo ">> Not mvn detected, running standalone sonar-scanner"
```suggestion
  echo ">> Maven not detected, running standalone sonar-scanner"
```

2020-11-26 14:19 UTC, gionn approved these changes

2020-11-26 17:02 UTC, merged