[semver:skip] Add 'download_repo' command
ClouDesire/circleci-orbs pull request #27
Opened 2020-12-04 12:56 UTC by PPFerrari

resolve #16

2020-12-04 14:51 UTC, gionn requested changes

2020-12-04 14:51 UTC, gionn commented on src/jobs/cookbooks_build.yml
> +  - git_download_repo:
git_checkout_repo?

2020-12-04 14:51 UTC, gionn commented on .circleci/config.yml
>    # Replace this with your own!
```suggestion
```

2020-12-04 14:51 UTC, gionn commented on src/scripts/download_repo.sh
> +  git clone -b $REPO_BRANCH git@github.com:ClouDesire/${REPO_NAME}.git ${REPO_DIR}/${REPO_NAME}
rendi parametrica anche l'organization

2020-12-04 14:53 UTC, PPFerrari commented on src/jobs/cookbooks_build.yml
> +  - git_download_repo:
il comando si chiama git_download_repo (scarica e fa il checkout). Potremmo anche chiamarlo `git_checkout_repo`.
Ho anteposto `git_` solo per poter visiamente raggruppare i comandi git.

2020-12-04 14:56 UTC, gionn commented on src/jobs/cookbooks_build.yml
> +  - git_download_repo:
download non corrisponde a nessun comando git noto, checkout mi sembra il compromesso migliore (fa quel che ti aspetteresti - è abbastanza ovvio che fa il clone prima)

2020-12-04 14:57 UTC, PPFerrari commented on src/scripts/download_repo.sh
> +  git clone -b $REPO_BRANCH git@github.com:ClouDesire/${REPO_NAME}.git ${REPO_DIR}/${REPO_NAME}
@gionn vogliamo rendere tutta la url più parametrica? quindi passando come variabile anche quello che ora è `github.com`.
Ero un po' indeciso al riguardo

2020-12-04 14:58 UTC, gionn commented on src/scripts/download_repo.sh
> +  git clone -b $REPO_BRANCH git@github.com:ClouDesire/${REPO_NAME}.git ${REPO_DIR}/${REPO_NAME}
se fai `git clone [remote-url] --branch [name] --single-branch [folder]` dovrebbe andare più forte (scarica solo l'ultimo commit e non tutta la history)

2020-12-07 13:37 UTC, gionn approved these changes

2020-12-07 15:00 UTC, merged