[semver:skip] Add 'maven_install_library' command
ClouDesire/circleci-orbs pull request #29
Opened 2020-12-04 16:35 UTC by PPFerrari

resolve https://github.com/ClouDesire/circleci-orbs/issues/28

This PR depends on https://github.com/ClouDesire/circleci-orbs/pull/27

2020-12-07 15:17 UTC, gionn requested changes

2020-12-07 15:17 UTC, gionn commented on src/scripts/java_install_library.sh
> +  set -e
questa feature potrebbe essere una opzione (abilitata di default) di git_checkout

2020-12-07 15:17 UTC, gionn commented on src/scripts/java_install_library.sh
> +  ./mvnw clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
non so se è meglio prevedere un override di tutto questo comando, come caso va bene comunque

2020-12-10 11:54 UTC, PPFerrari commented
@gionn credi sia più giusto inserire il comando `git_checkout` nel comando `maven_install_library`, oppure separarli e chiamarli sequenzialmente nei workflow? Per ora, `maven_install_library` nasce con l'idea di installare una libreria partendo da un repo, quindi era sembrato automatico inserire anche il comando di checkout.

2020-12-10 14:24 UTC, gionn requested changes

2020-12-10 14:24 UTC, gionn commented on src/scripts/java_install_library.sh
> +  git checkout "$CIRCLE_BRANCH" && git merge origin/master
ma qui non conviene riusare lo script di git_checkout?

2020-12-14 08:17 UTC, gionn approved these changes

2020-12-14 08:31 UTC, merged