[semver:skio] Add more parameters to git_checkout
ClouDesire/circleci-orbs pull request #31
Opened 2020-12-09 09:40 UTC by PPFerrari

Add the GIT_EMAIL and GIT_USERNAME parameters to set git global config for username and email. 
Also adds the MERGE_MASTER parameter (true by default). When this is true, the master branch is merged with the current CIRCLE_BRANCH.

2020-12-09 11:09 UTC, gionn requested changes

2020-12-09 11:09 UTC, gionn commented on src/commands/git_checkout.yml
> +        MERGE_MASTER: << parameters.merge_master >>
il top sarebbe se si potessero definire in un contesto, così da definire lì globalmente il valore, non credo ci sarà mai bisogno di customizzare nella singola build git_email e git_username, e di fatto stai già hardcodato questi valori negli altri orb

non so se si riesce a supportare in contemporanea con i parametri, forse preferirei definirli solo via context, se siamo costretti a scegliere una sola alternativa (fai fallire git_checkout.sh se quelle variabili non sono settate, oppure il default si setta direttamente lì)

2020-12-09 12:04 UTC, PPFerrari commented on src/commands/git_checkout.yml
> +        MERGE_MASTER: << parameters.merge_master >>
sì, sicuramente è meglio definirle in un context. Vedo se si può settare il valore di default di un parametro partendo da una variabile d'ambiente (ma non credo). Se non si può, li tolgo come parametri del comando e puntiamo direttamente alle variabili d'ambiente presa da context.

2020-12-09 14:41 UTC, PPFerrari commented on src/commands/git_checkout.yml
> +        MERGE_MASTER: << parameters.merge_master >>
Ho rimosso `git_email` e `git_username` come parametri. Lo script `git_checkot.sh` verifica come prima cosa se sono settati, se non lo sono ritorna errore.

2020-12-09 16:48 UTC, gionn requested changes

2020-12-09 16:48 UTC, gionn commented on src/scripts/git_checkout.sh
> +    set +e
sì il check puoi spostarlo qui dentro

2020-12-09 16:51 UTC, PPFerrari commented on src/scripts/git_checkout.sh
> +    set +e
ok, in questo modo non le rendiamo sempre obbligatorie, semplifichiamo un po'

2020-12-10 13:01 UTC, gionn requested changes

2020-12-10 14:29 UTC, gionn requested changes

2020-12-10 14:29 UTC, gionn commented on src/commands/git_checkout.yml
> +    description: Directory where to clone thr repository
```suggestion
    description: Directory where to clone the repository
```

2020-12-10 15:26 UTC, gionn requested changes

2020-12-10 15:26 UTC, gionn commented on src/scripts/git_checkout.sh
> +    git checkout "$CIRCLE_BRANCH" && git merge origin/$GIT_BASE_BRANCH
così non stai onorando il branch settato da parametro

2020-12-10 15:26 UTC, gionn commented on src/commands/git_checkout.yml
>      default: master
non so bene come, ma andrebbe gestito il caso del "usa lo stesso branch del branch corrente, se esiste, altrimenti default"

2020-12-10 16:46 UTC, PPFerrari commented on src/commands/git_checkout.yml
>      default: master
dai un'occhiata alle ultime modifiche appena pushate, fammi sapere se ti torna 👍

2020-12-10 17:14 UTC, gionn commented on src/scripts/git_checkout.sh
> +  fi
tutto molto bello ma credo basti provare a vedere se il branch esiste clonandolo (o con un altro comando che non ricordo) e se non esiste provare in sequenza master e poi main (voglio sperare che nessuno usi master/main per un branch diverso da quello di default)

così non serve per forza avere un github_token valido nel contesto

2020-12-11 08:10 UTC, gionn requested changes

2020-12-11 08:10 UTC, gionn commented on src/scripts/git_checkout.sh
> +          MERGE_MASTER=0
```suggestion
    if git ls-remote -h $REPO_URL | grep -q "${CIRCLE_BRANCH}"; then
      REPO_BRANCH="${CIRCLE_BRANCH}"
    elif git ls-remote -h $REPO_URL | grep -q "refs/heads/master"; then
      REPO_BRANCH="master"
      MERGE_MASTER=0
    elif git ls-remote -h $REPO_URL | grep -q "refs/heads/main"; then
      REPO_BRANCH="main"
      MERGE_MASTER=0
```

2020-12-11 15:38 UTC, gionn approved these changes

2020-12-11 16:40 UTC, merged