[semver:skip] add command, job and script for maven_release
ClouDesire/circleci-orbs pull request #70
Opened 2021-03-09 17:20 UTC by PPFerrari

ref https://github.com/ClouDesire/support/issues/4745

2021-03-12 10:45 UTC, gionn requested changes

2021-03-12 10:45 UTC, gionn commented on src/jobs/maven_release.yml
> +    default: 08:24:83:a8:59:c5:7d:d5:de:b3:15:bf:1a:50:0e:ca
ma se si usasse una variabile d'ambiente come default e poi si valorizza in un contesto di default?

penso sia più lineare da gestire

2021-03-12 10:45 UTC, gionn commented on src/jobs/maven_release.yml
> +            url: <<parameters.mvn_settings_repo>>
sono in dubbio, di solito il deploy è l'ultimo job di un workflow multi-job, e in tutti i nostri casi reali ci portiamo sempre dietro il workspace

forse si può fare attach del workspace e risparmiarci tutti questi step

2021-03-12 11:00 UTC, PPFerrari commented on src/jobs/maven_release.yml
> +    default: 08:24:83:a8:59:c5:7d:d5:de:b3:15:bf:1a:50:0e:ca
non saprei come passarla poi allo step `add_ssh_keys`, non essendo uno step bash non credo che possiamo passarla come variabile d'ambiente.

2021-03-12 11:20 UTC, PPFerrari commented on src/jobs/maven_release.yml
> +            url: <<parameters.mvn_settings_repo>>
Sì, potrebbe essere effettivamente una scelta migliore per il nostro caso. Potremmo parametrizzare il `path` del workspace di cui fare l'attach per renderlo leggermente più dinamico in caso di situazioni particolari. 

Lo step `add_ssh_keys` credo sia comunque necessario. 

Questo job nasce con questi step perché inizialmente l'idea era di avere un workflow dedicato, ma alla fine ho virato sull'avere un workflow unico `build-and-deploy` e condizionare l'esecuzione del job release al nome del branch.

2021-03-15 13:20 UTC, gionn approved these changes

2021-03-15 13:20 UTC, gionn commented
rilascia una minor e poi si prova su abstract-connector

2021-03-15 13:43 UTC, merged