[semver:patch] Add cache_key to invalidate m2 cache
ClouDesire/circleci-orbs pull request #74
Opened 2021-03-18 15:46 UTC by PPFerrari

ref https://github.com/ClouDesire/support/issues/4869

2021-03-18 16:05 UTC, gionn requested changes

2021-03-18 16:05 UTC, gionn commented on src/commands/maven_with_cache.yml
> +        - m2-<<parameters.cache_key>>
secondo me lo devi mette in tutte le keys sopra e anche nel save

2021-03-19 09:19 UTC, gionn commented
@pimuzzo prova l'ultima versione buildata nel repo che ti era esploso

2021-03-19 09:19 UTC, gionn approved these changes

2021-03-19 09:29 UTC, pimuzzo approved these changes
l'ha provata @PPFerrari  ieri mentre litigavo con il deployer :D

2021-03-19 09:33 UTC, merged