[semver:patch] edit maven release message
ClouDesire/circleci-orbs pull request #76
Opened 2021-03-23 08:56 UTC by PPFerrari

ref https://github.com/ClouDesire/support/issues/4745

2021-03-23 10:53 UTC, PPFerrari commented
Mergiata la PR, master/main vengono buildati correttamente: https://app.circleci.com/pipelines/github/ClouDesire/test-maven

2021-03-23 13:41 UTC, gionn requested changes

2021-03-23 13:41 UTC, gionn commented on src/scripts/maven_release.sh
> +  git commit -m "Preparing for next iteration - version set to ${NEW_VERSION}-SNAPSHOT" -m "" -m "[skip ci]"
qui il `\n` funzionerebbe asd

2021-03-23 13:41 UTC, gionn commented on src/scripts/maven_release.sh
> +  git add po*.xml
?

2021-03-23 13:41 UTC, gionn commented on src/scripts/maven_release.sh
> +  git push --set-upstream origin "${CIRCLE_BRANCH}"
set-upstream non ha granché senso per un branch creato e rimosso in automatico

2021-03-23 15:33 UTC, PPFerrari commented on src/scripts/maven_release.sh
> +  git push --set-upstream origin "${CIRCLE_BRANCH}"
l'ho aggiunto perché senza mi falliva così: 

```fatal: The current branch release has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin release```

2021-03-23 15:35 UTC, PPFerrari commented on src/scripts/maven_release.sh
> +  git commit -m "Preparing for next iteration - version set to ${NEW_VERSION}-SNAPSHOT" -m "" -m "[skip ci]"
`[release a7cb26b] Preparing for next iteration - version set to 0.6.4-SNAPSHOT \n \n [skip ci]`

vederlo scritto così mi ha fatto virare su quell'altra opzione di aggiungere più `-m ""` per ogni riga

2021-03-23 15:37 UTC, PPFerrari commented on src/scripts/maven_release.sh
> +  git add po*.xml
qui sicuramente mi puoi aiutare, volevo trovare e avere un modo per selezionare tutti i pom.xml modificati dal comando `mvn`. Purtroppo `git add .` mi prende anche `pomsum`

2021-03-24 08:35 UTC, gionn approved these changes

2021-03-24 08:36 UTC, merged