[semver:patch] add check on the HTTP_CODE returned by the curl
ClouDesire/circleci-orbs pull request #78
Opened 2021-03-26 15:55 UTC by PPFerrari

ref https://github.com/ClouDesire/support/issues/4906

2021-03-30 11:05 UTC, gionn requested changes

2021-03-30 11:05 UTC, gionn commented on src/scripts/utility_check_url.sh
> +HTTP_RESPONSE_CODE=$(docker run --network "container:${CONTAINER_NAME}" --rm curlimages/curl:7.75.0 -s -o /dev/null -w "%{http_code}" --retry "${CHECK_RETRIES}" --retry-delay ${SLEEP_TIME} --max-time
> -f, --fail
> 
> (HTTP) Fail silently (no output at all) on server errors. This is mostly done to enable scripts etc to better deal with failed attempts. In normal cases when an HTTP server fails to deliver a document, it returns an HTML document stating so (which often also describes why and more). This flag will prevent curl from outputting that and return error 22.
> 
> This method is not fail-safe and there are occasions where non-successful response codes will slip through, especially when authentication is involved (response codes 401 and 407). 

https://curl.se/docs/manpage.html

2021-03-30 11:11 UTC, PPFerrari commented on src/scripts/utility_check_url.sh
> +HTTP_RESPONSE_CODE=$(docker run --network "container:${CONTAINER_NAME}" --rm curlimages/curl:7.75.0 -s -o /dev/null -w "%{http_code}" --retry "${CHECK_RETRIES}" --retry-delay ${SLEEP_TIME} --max-time
lo aggiungo alle altre opzioni?

2021-03-30 14:39 UTC, gionn requested changes

2021-03-30 14:39 UTC, gionn commented on src/scripts/utility_check_url.sh
> +HTTP_RESPONSE_CODE=$(docker run --network "container:${CONTAINER_NAME}" --rm curlimages/curl:7.75.0 -s -o /dev/null -w "%{http_code}" --retry "${CHECK_RETRIES}" --retry-delay ${SLEEP_TIME} --max-time
non serve che ti parsi a mano il response code con `-f`, anche perché così non stai gestendo i `20x` che sono comunque response valide

2021-03-30 15:14 UTC, PPFerrari commented on src/scripts/utility_check_url.sh
> +HTTP_RESPONSE_CODE=$(docker run --network "container:${CONTAINER_NAME}" --rm curlimages/curl:7.75.0 -s -o /dev/null -w "%{http_code}" --retry "${CHECK_RETRIES}" --retry-delay ${SLEEP_TIME} --max-time
quindi dovrei uscire con errore solo se ritorna `error code 22`? Funziona anche chiamando la `curl` da dentro un container?

2021-03-31 08:01 UTC, gionn commented on src/scripts/utility_check_url.sh
> +HTTP_RESPONSE_CODE=$(docker run --network "container:${CONTAINER_NAME}" --rm curlimages/curl:7.75.0 -s -o /dev/null -w "%{http_code}" --retry "${CHECK_RETRIES}" --retry-delay ${SLEEP_TIME} --max-time
```
gionn at gt-g6 in ~/src/ops (master●)
$ docker run --rm "curlimages/curl:7.75.0" -f httpbin.org/status/500
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 500

gionn at gt-g6 in ~/src/ops (master●)
$ echo $?
22
```

2021-03-31 08:03 UTC, gionn commented on src/scripts/utility_check_url.sh
> +fi
or simply 

```suggestion
exit $?
```

2021-03-31 10:20 UTC, gionn approved these changes

2021-03-31 10:23 UTC, merged