[semver:minor] Create git_merge_master.sh
ClouDesire/circleci-orbs pull request #81
Opened 2021-03-30 14:36 UTC by PPFerrari

ref https://github.com/ClouDesire/support/issues/4913

2021-03-30 16:08 UTC, gionn requested changes

2021-03-30 16:08 UTC, gionn commented on src/scripts/git_merge_master.sh
> +  git config user.name "${GIT_USERNAME}"
https://github.com/ClouDesire/circleci-orbs/search?q=git+config+user.email

try to DRY

2021-03-30 16:18 UTC, PPFerrari commented on src/scripts/git_merge_master.sh
> +  git config user.name "${GIT_USERNAME}"
lo so, vedevo anche io ci sono pezzi di codice ripetuto. Probabilmente l'unico modo sarebbe fare dei comandi con gli step multipli, che richiamano script. Tipo in questo caso, uno script che fa la config di `user` e `mail` per `git`.

2021-03-31 10:54 UTC, gionn commented on README.md
> +          command: ./mvnw -B package
```suggestion
      - run: # current tree is now aligned with the current default branch
```

o forse proprio nulla?

2021-03-31 11:02 UTC, PPFerrari commented on README.md
> +          command: ./mvnw -B package
lo avevo messo per dare un contesto di esempio di dove usarlo, in questo caso prima di fare la build di qualcosa. 
In caso, non lo eliminerei proprio.

2021-03-31 12:30 UTC, gionn approved these changes

2021-03-31 12:46 UTC, merged