[semver:minor] Add same_remote_branch in git_checkout command
ClouDesire/circleci-orbs pull request #93
Opened 2021-04-07 13:12 UTC by PPFerrari

ref https://github.com/ClouDesire/support/issues/4944﻿

2021-04-07 16:09 UTC, gionn requested changes

2021-04-07 16:09 UTC, gionn commented on src/scripts/git_check_remote_branch.sh
> +echo "export REMOTE_BRANCH_EXISTS=${REMOTE_BRANCH_EXISTS}" >> "${HOME}/globals.sh"
eee ma i REPO_URL non possono essere tanti?

2021-04-08 07:43 UTC, PPFerrari commented on src/scripts/git_check_remote_branch.sh
> +echo "export REMOTE_BRANCH_EXISTS=${REMOTE_BRANCH_EXISTS}" >> "${HOME}/globals.sh"
sì, in effetti qualcuno potrebbe fare checkout di più repo e voler verificare. Ci aggiungo il nome del repo all'inizio della variabile `REMOTE_BRANCH_EXISTS`

2021-04-08 08:05 UTC, PPFerrari commented on src/commands/maven_install_library.yml
> +              fi
ho rimosso lo script esterno e inserito tutti qui, in un unico comando, per semplificare anche la situazione di più repo scaricati. Credo così sia più semplice e pulito. 
Ho ancora dei dubbi sul fatto che questo controlla sia fatti qui, invece che su `git_checkout`. Su quest'ultimo potrebbe essere un caso particolare, nel quale fare download del repository solo se in remoto ha lo stesso branch della PR.

2021-04-08 08:32 UTC, gionn requested changes

2021-04-08 08:32 UTC, gionn commented on src/commands/maven_install_library.yml
> +  Install a java library from a git repo. the command checks if on
```suggestion
  Install a java library from a git repo. If repo_branch is undefined, the command checks if on
```

2021-04-08 08:32 UTC, gionn commented on src/commands/maven_install_library.yml
> +      branch of the library repository to checkout. If not passed,
```suggestion
      branch of the library repository to checkout. If unset,
```

2021-04-08 09:33 UTC, gionn approved these changes

2021-04-08 09:48 UTC, merged